<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Storage;
use App\Models\Admin;
use App\Models\Course;
use App\Models\CourseCategory;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            [
                'slug' => 'web-development',
                'name' => 'Web Development',
                'name_ar' => 'تطوير الويب',
                'description' => 'Hands-on coding categories covering modern full-stack development skills.',
                'description_ar' => 'دورات عملية تغطي مهارات تطوير الويب الحديثة من الواجهة إلى الخلفية.',
                'is_featured' => true,
            ],
            [
                'slug' => 'data-science',
                'name' => 'Data Science',
                'name_ar' => 'علوم البيانات',
                'description' => 'Analytical programs that unlock the power of data-driven decision making.',
                'description_ar' => 'برامج تحليلية تساعدك على اتخاذ القرارات بناءً على البيانات.',
                'is_featured' => true,
            ],
            [
                'slug' => 'digital-marketing',
                'name' => 'Digital Marketing',
                'name_ar' => 'التسويق الرقمي',
                'description' => 'Strategies and toolkits for creating impactful digital campaigns.',
                'description_ar' => 'استراتيجيات وأدوات لإنشاء حملات رقمية فعّالة.',
                'is_featured' => false,
            ],
            [
                'slug' => 'business-management',
                'name' => 'Business Management',
                'name_ar' => 'إدارة الأعمال',
                'description' => 'Leadership and operational excellence for modern organizations.',
                'description_ar' => 'القيادة والتميز التشغيلي في المنظمات الحديثة.',
                'is_featured' => false,
            ],
            [
                'slug' => 'graphic-design',
                'name' => 'Graphic Design',
                'name_ar' => 'التصميم الجرافيكي',
                'description' => 'Creative courses for building captivating visual experiences.',
                'description_ar' => 'دورات إبداعية لبناء تجارب بصرية جذابة.',
                'is_featured' => true,
            ],
        ];

        $categoryMap = [];

        foreach ($categories as $categoryData) {
            $category = CourseCategory::updateOrCreate(
                ['slug' => $categoryData['slug']],
                Arr::only($categoryData, [
                    'name',
                    'name_ar',
                    'description',
                    'description_ar',
                    'is_featured',
                ])
            );

            $categoryMap[$categoryData['slug']] = $category->id;
        }

        $instructors = Admin::query()
            ->whereHas('adminType', fn ($query) => $query->where('name', 'instructor'))
            ->active()
            ->get();

        if ($instructors->isEmpty()) {
            $this->command?->warn('No active instructors found. Please run the InstructorSeeder first.');
            return;
        }

        $organisation = [
            '@type' => 'Organization',
            'name' => 'E-Class Academy',
            'url' => 'https://eclass.test',
        ];

        $courses = [
            [
                'name' => 'Full-Stack Web Development Bootcamp',
                'name_ar' => 'معسكر تطوير الويب المتكامل',
                'description' => 'A project-based program covering modern frontend, backend, and deployment workflows for full-stack engineers.',
                'description_ar' => 'برنامج قائم على المشاريع يغطي أحدث أساليب الواجهة والخلفية وعمليات النشر للمهندسين متعددي المهارات.',
                'category_slug' => 'web-development',
                'duration' => '12 weeks',
                'price' => 1199.00,
                'original_price' => 1499.00,
                'image' => 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80',
                'preview_video_url' => 'https://www.youtube.com/watch?v=Ke90Tje7VS0',
                'certificate_template' => 'certificates/default-template.pdf',
                'certificate_text' => 'Certificate awarded upon successful completion of the Full-Stack Web Development Bootcamp.',
                'certificate_text_ar' => 'شهادة تمنح بعد إكمال معسكر تطوير الويب المتكامل بنجاح.',
                'book' => 'books/full-stack-web-development-guide.pdf',
                'what_to_learn' => [
                    'Build RESTful APIs with Laravel and Express.',
                    'Craft responsive interfaces using Tailwind CSS and Vue.',
                    'Deploy production-ready applications to cloud platforms.',
                ],
                'what_to_learn_ar' => [
                    'بناء واجهات برمجية REST باستخدام Laravel وExpress.',
                    'إنشاء واجهات متجاوبة باستخدام Tailwind CSS وVue.',
                    'نشر التطبيقات الجاهزة للإنتاج على منصات سحابية.',
                ],
                'faq_course' => [
                    [
                        'question' => 'Do I need prior coding experience?',
                        'answer' => 'Basic familiarity with HTML and CSS is recommended, but the bootcamp starts with fundamentals.',
                    ],
                    [
                        'question' => 'Is there a capstone project?',
                        'answer' => 'Yes, you will build and deploy a full-stack project evaluated by instructors.',
                    ],
                ],
                'faq_course_ar' => [
                    [
                        'question' => 'هل أحتاج إلى خبرة سابقة في البرمجة؟',
                        'answer' => 'يُفضل الإلمام الأساسي بـ HTML وCSS، لكن المعسكر يبدأ من الأساسيات.',
                    ],
                    [
                        'question' => 'هل يوجد مشروع تخرج؟',
                        'answer' => 'نعم، ستقوم ببناء ونشر مشروع متكامل يتم تقييمه من قبل المدربين.',
                    ],
                ],
                'requirements' => 'A laptop capable of running Docker and modern browsers.',
                'requirements_ar' => 'جهاز حاسوب محمول قادر على تشغيل Docker والمتصفحات الحديثة.',
                'is_featured' => true,
                'show_in_top_discounted' => true,
                'show_in_subscription_bundles' => false,
                'show_in_live_meeting' => false,
                'show_in_recent_courses' => true,
                'is_free' => false,
                'total_lessons' => 96,
                'total_duration_minutes' => 540,
                'enrolled_students' => 420,
                'completion_rate' => 78,
                'average_rating' => 4.7,
                'total_ratings' => 185,
                'total_reviews' => 132,
                'meta_title' => 'Full-Stack Web Development Bootcamp',
                'meta_title_ar' => 'معسكر تطوير الويب المتكامل',
                'meta_description' => 'Master modern full-stack development with Laravel, Vue, and cloud deployment in 12 weeks.',
                'meta_description_ar' => 'أتقن تطوير الويب المتكامل باستخدام Laravel وVue خلال 12 أسبوعًا.',
                'meta_keywords' => 'web development bootcamp, laravel course, vue training',
                'meta_keywords_ar' => 'تطوير الويب, دورة لارافيل, دورة فيو',
                'canonical_url' => 'https://eclass.test/courses/full-stack-web-development-bootcamp',
                'og_title' => 'Become a Full-Stack Developer in 12 Weeks',
                'og_title_ar' => 'أصبح مطور ويب متكامل خلال 12 أسبوعًا',
                'og_description' => 'Join our immersive bootcamp to build and deploy production-ready web apps.',
                'og_description_ar' => 'انضم إلى معسكرنا العملي لبناء تطبيقات ويب جاهزة للإطلاق.',
                'og_image' => 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80',
                'twitter_title' => 'Full-Stack Web Development Bootcamp',
                'twitter_title_ar' => 'معسكر تطوير الويب المتكامل',
                'twitter_description' => 'Hands-on full-stack training with expert mentors and real-world projects.',
                'twitter_description_ar' => 'تدريب عملي مع مدربين خبراء ومشاريع حقيقية.',
                'twitter_image' => 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80',
                'structured_data' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'Full-Stack Web Development Bootcamp',
                    'description' => 'A 12-week intensive that takes you from fundamentals to deploying full-stack apps.',
                    'provider' => $organisation,
                ],
                'structured_data_ar' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'معسكر تطوير الويب المتكامل',
                    'description' => 'برنامج مكثف لمدة 12 أسبوعًا يأخذك من الأساسيات إلى نشر التطبيقات.',
                    'provider' => $organisation,
                ],
                'supported_languages' => ['en', 'ar'],
                'default_language' => 'en',
            ],
            [
                'name' => 'Advanced JavaScript for Professionals',
                'name_ar' => 'جافاسكريبت المتقدمة للمحترفين',
                'description' => 'An advanced JavaScript and TypeScript curriculum focused on architecture, performance, and real-world patterns.',
                'description_ar' => 'منهج متقدم في جافاسكريبت وتايب سكريبت يركز على الهندسة والأداء والأنماط العملية.',
                'category_slug' => 'web-development',
                'duration' => '6 weeks',
                'price' => 749.00,
                'original_price' => 899.00,
                'image' => 'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?auto=format&fit=crop&w=1200&q=80',
                'preview_video_url' => 'https://www.youtube.com/watch?v=Oe421EPjeBE',
                'certificate_template' => null,
                'certificate_text' => null,
                'certificate_text_ar' => null,
                'book' => 'books/advanced-javascript-patterns.pdf',
                'what_to_learn' => [
                    'Master asynchronous patterns and event loops.',
                    'Implement scalable architecture with TypeScript.',
                    'Optimize performance with modern tooling.',
                ],
                'what_to_learn_ar' => [
                    'إتقان الأنماط غير المتزامنة وحلقات الأحداث.',
                    'تنفيذ بنى قابلة للتوسع باستخدام TypeScript.',
                    'تحسين الأداء باستخدام الأدوات الحديثة.',
                ],
                'faq_course' => [
                    [
                        'question' => 'Is this course framework-specific?',
                        'answer' => 'The course focuses on core JavaScript and TypeScript concepts that apply across frameworks.',
                    ],
                ],
                'faq_course_ar' => [
                    [
                        'question' => 'هل تركز الدورة على إطار عمل محدد؟',
                        'answer' => 'تركز الدورة على مفاهيم جافاسكريبت وتايب سكريبت الأساسية القابلة للتطبيق على جميع الأطر.',
                    ],
                ],
                'requirements' => 'Solid understanding of ES6 syntax and modern tooling.',
                'requirements_ar' => 'فهم قوي لـ ES6 والأدوات الحديثة.',
                'is_featured' => false,
                'show_in_top_discounted' => false,
                'show_in_subscription_bundles' => true,
                'show_in_live_meeting' => false,
                'show_in_recent_courses' => true,
                'is_free' => false,
                'total_lessons' => 48,
                'total_duration_minutes' => 310,
                'enrolled_students' => 260,
                'completion_rate' => 84,
                'average_rating' => 4.8,
                'total_ratings' => 94,
                'total_reviews' => 71,
                'meta_title' => 'Advanced JavaScript for Professionals',
                'meta_title_ar' => 'جافاسكريبت المتقدمة للمحترفين',
                'meta_description' => 'Level up your JavaScript expertise with advanced patterns, TypeScript, and performance techniques.',
                'meta_description_ar' => 'ارفع مهاراتك في جافاسكريبت مع الأنماط المتقدمة وتايب سكريبت.',
                'meta_keywords' => 'advanced javascript, typescript course, js performance',
                'meta_keywords_ar' => 'جافاسكريبت متقدمة, دورة تايب سكريبت',
                'canonical_url' => 'https://eclass.test/courses/advanced-javascript-for-professionals',
                'og_title' => 'Become a JavaScript Power User',
                'og_title_ar' => 'أصبح خبيرًا في جافاسكريبت',
                'og_description' => 'Deep dive into advanced JavaScript techniques used by top engineering teams.',
                'og_description_ar' => 'تعرف على التقنيات المتقدمة في جافاسكريبت المستخدمة من قبل الفرق العالمية.',
                'og_image' => 'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?auto=format&fit=crop&w=1200&q=80',
                'twitter_title' => 'Advanced JavaScript for Professionals',
                'twitter_title_ar' => 'جافاسكريبت المتقدمة للمحترفين',
                'twitter_description' => 'Master async patterns, TypeScript, and high-performance JavaScript.',
                'twitter_description_ar' => 'أتقن الأنماط غير المتزامنة وتايب سكريبت وأداء جافاسكريبت.',
                'twitter_image' => 'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?auto=format&fit=crop&w=1200&q=80',
                'structured_data' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'Advanced JavaScript for Professionals',
                    'description' => 'An advanced program for engineers who want to master modern JavaScript.',
                    'provider' => $organisation,
                ],
                'structured_data_ar' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'جافاسكريبت المتقدمة للمحترفين',
                    'description' => 'برنامج متقدم للمهندسين لإتقان جافاسكريبت الحديثة.',
                    'provider' => $organisation,
                ],
                'supported_languages' => ['en', 'ar'],
                'default_language' => 'en',
            ],
            [
                'name' => 'Modern Frontend Architectures with React & Vue',
                'name_ar' => 'هندسة الواجهات الحديثة باستخدام React وVue',
                'description' => 'Design scalable frontend platforms using modern architecture patterns, design systems, and collaboration practices.',
                'description_ar' => 'صمم منصات واجهات قابلة للتوسع باستخدام أنماط هندسة حديثة وأنظمة تصميم وممارسات تعاون فعّالة.',
                'category_slug' => 'web-development',
                'duration' => '8 weeks',
                'price' => 879.00,
                'original_price' => 1049.00,
                'image' => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
                'preview_video_url' => 'https://www.youtube.com/watch?v=Tn6-PIqc4UM',
                'certificate_template' => 'certificates/frontend-architecture.pdf',
                'certificate_text' => 'Certificate issued for mastering modern frontend architecture patterns.',
                'certificate_text_ar' => 'شهادة تمنح لإتقان أنماط هندسة الواجهات الحديثة.',
                'book' => null,
                'what_to_learn' => [
                    'Design micro-frontend strategies for large teams.',
                    'Implement reusable component systems with Storybook.',
                    'Automate quality gates with CI/CD workflows.',
                ],
                'what_to_learn_ar' => [
                    'تصميم استراتيجيات Micro-Frontends للفرق الكبيرة.',
                    'تنفيذ أنظمة مكونات قابلة لإعادة الاستخدام باستخدام Storybook.',
                    'أتمتة الجودة باستخدام CI/CD.',
                ],
                'faq_course' => [
                    [
                        'question' => 'Does the course cover testing strategies?',
                        'answer' => 'Yes, we cover unit, integration, and visual regression testing.',
                    ],
                ],
                'faq_course_ar' => [
                    [
                        'question' => 'هل تغطي الدورة استراتيجيات الاختبار؟',
                        'answer' => 'نعم، نغطي الاختبارات الوحدوية والتكاملية واختبارات الواجهة.',
                    ],
                ],
                'requirements' => 'Experience building SPAs with React or Vue.',
                'requirements_ar' => 'خبرة في بناء تطبيقات الصفحة الواحدة باستخدام React أو Vue.',
                'is_featured' => true,
                'show_in_top_discounted' => false,
                'show_in_subscription_bundles' => true,
                'show_in_live_meeting' => true,
                'show_in_recent_courses' => true,
                'is_free' => false,
                'total_lessons' => 64,
                'total_duration_minutes' => 420,
                'enrolled_students' => 190,
                'completion_rate' => 82,
                'average_rating' => 4.6,
                'total_ratings' => 75,
                'total_reviews' => 58,
                'meta_title' => 'Modern Frontend Architectures with React & Vue',
                'meta_title_ar' => 'هندسة الواجهات الحديثة باستخدام React وVue',
                'meta_description' => 'Architect scalable frontend systems with React, Vue, and modern tooling.',
                'meta_description_ar' => 'صمم أنظمة واجهات قابلة للتوسع باستخدام React وVue.',
                'meta_keywords' => 'react architecture, vue architecture, frontend course',
                'meta_keywords_ar' => 'هندسة الواجهات, دورة React, دورة Vue',
                'canonical_url' => 'https://eclass.test/courses/modern-frontend-architectures-react-vue',
                'og_title' => 'Architect Modern Frontend Systems',
                'og_title_ar' => 'صمم أنظمة واجهات حديثة',
                'og_description' => 'Learn architecture patterns, tooling, and workflows for enterprise frontends.',
                'og_description_ar' => 'تعلم أنماط الهندسة والأدوات للواجهات المؤسسية.',
                'og_image' => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
                'twitter_title' => 'Modern Frontend Architectures',
                'twitter_title_ar' => 'هندسة الواجهات الحديثة',
                'twitter_description' => 'Design scalable frontend platforms with React, Vue, and Storybook.',
                'twitter_description_ar' => 'صمم منصات واجهات قابلة للتوسع باستخدام React وVue.',
                'twitter_image' => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
                'structured_data' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'Modern Frontend Architectures with React & Vue',
                    'description' => 'Design scalable frontend systems and workflows with React and Vue.',
                    'provider' => $organisation,
                ],
                'structured_data_ar' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'هندسة الواجهات الحديثة باستخدام React وVue',
                    'description' => 'تعلم تصميم أنظمة واجهات قابلة للتوسع باستخدام React وVue.',
                    'provider' => $organisation,
                ],
                'supported_languages' => ['en', 'ar'],
                'default_language' => 'en',
            ],
            [
                'name' => 'Data Science & Machine Learning with Python',
                'name_ar' => 'علوم البيانات وتعلم الآلة باستخدام بايثون',
                'description' => 'Hands-on labs that teach end-to-end data science workflows from exploration through model deployment.',
                'description_ar' => 'مختبرات عملية تعلمك سير عمل علوم البيانات من الاستكشاف إلى نشر النماذج.',
                'category_slug' => 'data-science',
                'duration' => '10 weeks',
                'price' => 1299.00,
                'original_price' => 1599.00,
                'image' => 'https://images.unsplash.com/photo-1529101091764-c3526daf38fe?auto=format&fit=crop&w=1200&q=80',
                'preview_video_url' => 'https://www.youtube.com/watch?v=7eh4d6sabA0',
                'certificate_template' => 'certificates/data-science.pdf',
                'certificate_text' => 'Certificate awarded for completing the Data Science & Machine Learning program.',
                'certificate_text_ar' => 'شهادة تمنح بعد إكمال برنامج علوم البيانات وتعلم الآلة.',
                'book' => 'books/data-science-lab-notebook.pdf',
                'what_to_learn' => [
                    'Clean and explore datasets using pandas and NumPy.',
                    'Build predictive models with scikit-learn.',
                    'Deploy machine learning models with FastAPI.',
                ],
                'what_to_learn_ar' => [
                    'تنظيف واستكشاف البيانات باستخدام pandas وNumPy.',
                    'بناء نماذج تنبؤية باستخدام scikit-learn.',
                    'نشر نماذج تعلم الآلة باستخدام FastAPI.',
                ],
                'faq_course' => [
                    [
                        'question' => 'Is math knowledge required?',
                        'answer' => 'Comfort with high-school algebra and statistics helps but we provide refreshers.',
                    ],
                ],
                'faq_course_ar' => [
                    [
                        'question' => 'هل أحتاج إلى معرفة رياضية؟',
                        'answer' => 'الإلمام بالجبر والإحصاء مفيد، ونوفر مراجعات سريعة.',
                    ],
                ],
                'requirements' => 'Laptop with Python 3.10+, 8GB RAM minimum.',
                'requirements_ar' => 'حاسوب محمول مع Python 3.10+ وذاكرة 8 جيجابايت على الأقل.',
                'is_featured' => true,
                'show_in_top_discounted' => true,
                'show_in_subscription_bundles' => true,
                'show_in_live_meeting' => true,
                'show_in_recent_courses' => true,
                'is_free' => false,
                'total_lessons' => 80,
                'total_duration_minutes' => 510,
                'enrolled_students' => 380,
                'completion_rate' => 71,
                'average_rating' => 4.5,
                'total_ratings' => 160,
                'total_reviews' => 114,
                'meta_title' => 'Data Science & Machine Learning with Python',
                'meta_title_ar' => 'علوم البيانات وتعلم الآلة باستخدام بايثون',
                'meta_description' => 'Build end-to-end machine learning pipelines and deploy real-world solutions.',
                'meta_description_ar' => 'ابنِ نماذج تعلم الآلة كاملة واطلق حلولًا واقعية.',
                'meta_keywords' => 'data science course, machine learning python, ml pipeline',
                'meta_keywords_ar' => 'علوم البيانات, تعلم الآلة, بايثون',
                'canonical_url' => 'https://eclass.test/courses/data-science-machine-learning-python',
                'og_title' => 'Launch Your Data Science Career',
                'og_title_ar' => 'ابدأ مسيرتك في علوم البيانات',
                'og_description' => 'Hands-on labs, projects, and mentorship to master machine learning.',
                'og_description_ar' => 'مختبرات عملية ومشاريع وإرشاد لإتقان تعلم الآلة.',
                'og_image' => 'https://images.unsplash.com/photo-1529101091764-c3526daf38fe?auto=format&fit=crop&w=1200&q=80',
                'twitter_title' => 'Data Science & ML with Python',
                'twitter_title_ar' => 'علوم البيانات وتعلم الآلة',
                'twitter_description' => 'From exploratory data analysis to deploying models in production.',
                'twitter_description_ar' => 'من تحليل البيانات إلى نشر النماذج في الإنتاج.',
                'twitter_image' => 'https://images.unsplash.com/photo-1529101091764-c3526daf38fe?auto=format&fit=crop&w=1200&q=80',
                'structured_data' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'Data Science & Machine Learning with Python',
                    'description' => 'Master the end-to-end machine learning workflow with Python.',
                    'provider' => $organisation,
                ],
                'structured_data_ar' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'علوم البيانات وتعلم الآلة باستخدام بايثون',
                    'description' => 'أتقن سير عمل تعلم الآلة الكامل باستخدام بايثون.',
                    'provider' => $organisation,
                ],
                'supported_languages' => ['en', 'ar'],
                'default_language' => 'en',
            ],
            [
                'name' => 'Applied AI for Business Leaders',
                'name_ar' => 'الذكاء الاصطناعي التطبيقي لقادة الأعمال',
                'description' => 'Strategic guidance for executives to identify, govern, and scale high-impact AI initiatives.',
                'description_ar' => 'إرشاد استراتيجي للقيادات لتحديد مبادرات الذكاء الاصطناعي عالية التأثير وحوكمتها وتوسيعها.',
                'category_slug' => 'data-science',
                'duration' => '4 weeks',
                'price' => 549.00,
                'original_price' => 699.00,
                'image' => 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=1200&q=80',
                'preview_video_url' => 'https://www.youtube.com/watch?v=2ePf9rue1Ao',
                'certificate_template' => null,
                'certificate_text' => null,
                'certificate_text_ar' => null,
                'book' => 'books/applied-ai-playbook.pdf',
                'what_to_learn' => [
                    'Identify business cases suitable for AI initiatives.',
                    'Design responsible AI governance frameworks.',
                    'Measure ROI and scale AI programs effectively.',
                ],
                'what_to_learn_ar' => [
                    'تحديد حالات الأعمال المناسبة لمبادرات الذكاء الاصطناعي.',
                    'تصميم أطر حوكمة مسؤولة للذكاء الاصطناعي.',
                    'قياس العائد وتوسيع برامج الذكاء الاصطناعي بفعالية.',
                ],
                'faq_course' => [
                    [
                        'question' => 'Is this a technical course?',
                        'answer' => 'The course focuses on strategy and leadership with optional technical deep dives.',
                    ],
                ],
                'faq_course_ar' => [
                    [
                        'question' => 'هل هذه دورة تقنية؟',
                        'answer' => 'تركز الدورة على الإستراتيجية والقيادة مع أجزاء تقنية اختيارية.',
                    ],
                ],
                'requirements' => 'Experience leading digital or analytics initiatives.',
                'requirements_ar' => 'خبرة في قيادة المبادرات الرقمية أو التحليلية.',
                'is_featured' => false,
                'show_in_top_discounted' => false,
                'show_in_subscription_bundles' => true,
                'show_in_live_meeting' => true,
                'show_in_recent_courses' => false,
                'is_free' => false,
                'total_lessons' => 24,
                'total_duration_minutes' => 180,
                'enrolled_students' => 145,
                'completion_rate' => 88,
                'average_rating' => 4.4,
                'total_ratings' => 52,
                'total_reviews' => 37,
                'meta_title' => 'Applied AI for Business Leaders',
                'meta_title_ar' => 'الذكاء الاصطناعي التطبيقي لقادة الأعمال',
                'meta_description' => 'Learn how to build AI roadmaps, governance, and ROI measurement frameworks.',
                'meta_description_ar' => 'تعلم كيفية بناء خارطة طريق للذكاء الاصطناعي وأطر الحوكمة وقياس العائد.',
                'meta_keywords' => 'ai strategy course, business ai leadership',
                'meta_keywords_ar' => 'استراتيجية الذكاء الاصطناعي, قيادة الأعمال',
                'canonical_url' => 'https://eclass.test/courses/applied-ai-for-business-leaders',
                'og_title' => 'Lead AI Transformation Initiatives',
                'og_title_ar' => 'قد مبادرات التحول بالذكاء الاصطناعي',
                'og_description' => 'Frameworks and playbooks to deliver business value with AI.',
                'og_description_ar' => 'أطر وعملية لتحقيق قيمة الأعمال باستخدام الذكاء الاصطناعي.',
                'og_image' => 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=1200&q=80',
                'twitter_title' => 'Applied AI for Business Leaders',
                'twitter_title_ar' => 'الذكاء الاصطناعي التطبيقي لقادة الأعمال',
                'twitter_description' => 'Translate AI potential into measurable business outcomes.',
                'twitter_description_ar' => 'ترجم إمكانات الذكاء الاصطناعي إلى نتائج أعمال ملموسة.',
                'twitter_image' => 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=1200&q=80',
                'structured_data' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'Applied AI for Business Leaders',
                    'description' => 'Strategic frameworks to lead AI programs and deliver business value.',
                    'provider' => $organisation,
                ],
                'structured_data_ar' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'الذكاء الاصطناعي التطبيقي لقادة الأعمال',
                    'description' => 'أطر إستراتيجية لقيادة برامج الذكاء الاصطناعي وتحقيق قيمة الأعمال.',
                    'provider' => $organisation,
                ],
                'supported_languages' => ['en', 'ar'],
                'default_language' => 'en',
            ],
            [
                'name' => 'SQL Analytics & Data Visualization',
                'name_ar' => 'تحليلات SQL وتصوير البيانات',
                'description' => 'Develop advanced SQL skills and communicate insights with professional dashboards and storytelling.',
                'description_ar' => 'طوّر مهارات SQL المتقدمة وقدم الرؤى من خلال لوحات احترافية وسرد قصصي.',
                'category_slug' => 'data-science',
                'duration' => '5 weeks',
                'price' => 399.00,
                'original_price' => 499.00,
                'image' => 'https://images.unsplash.com/photo-1483721310020-03333e577078?auto=format&fit=crop&w=1200&q=80',
                'preview_video_url' => 'https://www.youtube.com/watch?v=HXV3zeQKqGY',
                'certificate_template' => null,
                'certificate_text' => null,
                'certificate_text_ar' => null,
                'book' => 'books/sql-analytics-dashboarding.pdf',
                'what_to_learn' => [
                    'Write analytical SQL queries for complex datasets.',
                    'Model data in modern warehouses like BigQuery.',
                    'Build interactive dashboards with Metabase.',
                ],
                'what_to_learn_ar' => [
                    'كتابة استعلامات SQL تحليلية لبيانات معقدة.',
                    'نمذجة البيانات في مخازن حديثة مثل BigQuery.',
                    'إنشاء لوحات تفاعلية باستخدام Metabase.',
                ],
                'faq_course' => [
                    [
                        'question' => 'Will we cover SQL window functions?',
                        'answer' => 'Yes, you will master window functions, CTEs, and advanced aggregations.',
                    ],
                ],
                'faq_course_ar' => [
                    [
                        'question' => 'هل سنغطي دوال النوافذ في SQL؟',
                        'answer' => 'نعم، ستتقن دوال النوافذ وCTE والتجميعات المتقدمة.',
                    ],
                ],
                'requirements' => 'Basic SQL knowledge and access to a data warehouse (practice datasets provided).',
                'requirements_ar' => 'معرفة أساسية بـ SQL والوصول إلى مخزن بيانات (نوفر مجموعات بيانات للتدريب).',
                'is_featured' => false,
                'show_in_top_discounted' => true,
                'show_in_subscription_bundles' => false,
                'show_in_live_meeting' => false,
                'show_in_recent_courses' => true,
                'is_free' => false,
                'total_lessons' => 28,
                'total_duration_minutes' => 200,
                'enrolled_students' => 310,
                'completion_rate' => 91,
                'average_rating' => 4.3,
                'total_ratings' => 112,
                'total_reviews' => 80,
                'meta_title' => 'SQL Analytics & Data Visualization',
                'meta_title_ar' => 'تحليلات SQL وتصوير البيانات',
                'meta_description' => 'Deliver compelling analytics with advanced SQL and dashboarding best practices.',
                'meta_description_ar' => 'قدم تحليلات قوية باستخدام SQL المتقدم وأفضل ممارسات العرض.',
                'meta_keywords' => 'sql analytics, data visualization course, dashboards',
                'meta_keywords_ar' => 'تحليلات SQL, تصور البيانات',
                'canonical_url' => 'https://eclass.test/courses/sql-analytics-data-visualization',
                'og_title' => 'Tell Better Stories with Data',
                'og_title_ar' => 'اخلق قصصًا أفضل بالبيانات',
                'og_description' => 'Master SQL analytics and build dashboards stakeholders love.',
                'og_description_ar' => 'أتقن تحليلات SQL وأنشئ لوحات يحبها أصحاب المصلحة.',
                'og_image' => 'https://images.unsplash.com/photo-1483721310020-03333e577078?auto=format&fit=crop&w=1200&q=80',
                'twitter_title' => 'SQL Analytics & Visualization',
                'twitter_title_ar' => 'تحليلات SQL وتصوير البيانات',
                'twitter_description' => 'Turn raw data into actionable insights with SQL and Metabase.',
                'twitter_description_ar' => 'حوّل البيانات الخام إلى رؤى قابلة للتنفيذ باستخدام SQL وMetabase.',
                'twitter_image' => 'https://images.unsplash.com/photo-1483721310020-03333e577078?auto=format&fit=crop&w=1200&q=80',
                'structured_data' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'SQL Analytics & Data Visualization',
                    'description' => 'Learn advanced SQL and dashboard design to communicate data insights.',
                    'provider' => $organisation,
                ],
                'structured_data_ar' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'تحليلات SQL وتصوير البيانات',
                    'description' => 'تعلم SQL المتقدم وتصميم لوحات لتوصيل رؤى البيانات.',
                    'provider' => $organisation,
                ],
                'supported_languages' => ['en', 'ar'],
                'default_language' => 'en',
            ],
            [
                'name' => 'Digital Marketing Strategy & Analytics',
                'name_ar' => 'استراتيجية التسويق الرقمي والتحليلات',
                'description' => 'Comprehensive playbook for building, executing, and measuring multi-channel digital marketing strategies.',
                'description_ar' => 'دليل متكامل لبناء وتنفيذ وقياس استراتيجيات التسويق الرقمي متعددة القنوات.',
                'category_slug' => 'digital-marketing',
                'duration' => '6 weeks',
                'price' => 599.00,
                'original_price' => 749.00,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
                'preview_video_url' => 'https://www.youtube.com/watch?v=nU-IIXBWlS4',
                'certificate_template' => null,
                'certificate_text' => null,
                'certificate_text_ar' => null,
                'book' => 'books/digital-marketing-scorecard.pdf',
                'what_to_learn' => [
                    'Plan full-funnel digital campaigns with measurable KPIs.',
                    'Use GA4 and Looker Studio for marketing analytics.',
                    'Allocate budgets using attribution modeling.',
                ],
                'what_to_learn_ar' => [
                    'تخطيط حملات رقمية متكاملة مع مؤشرات أداء قابلة للقياس.',
                    'استخدام GA4 وLooker Studio لتحليلات التسويق.',
                    'توزيع الميزانيات باستخدام نماذج الإسناد.',
                ],
                'faq_course' => [
                    [
                        'question' => 'Do you cover paid advertising platforms?',
                        'answer' => 'Yes, we cover Google Ads, Meta Ads, and LinkedIn campaign best practices.',
                    ],
                ],
                'faq_course_ar' => [
                    [
                        'question' => 'هل تغطي الدورة منصات الإعلانات المدفوعة؟',
                        'answer' => 'نعم، نغطي Google Ads وMeta Ads وLinkedIn.',
                    ],
                ],
                'requirements' => 'Familiarity with marketing fundamentals and analytics terminology.',
                'requirements_ar' => 'الإلمام بأساسيات التسويق ومصطلحات التحليلات.',
                'is_featured' => true,
                'show_in_top_discounted' => false,
                'show_in_subscription_bundles' => true,
                'show_in_live_meeting' => false,
                'show_in_recent_courses' => true,
                'is_free' => false,
                'total_lessons' => 36,
                'total_duration_minutes' => 240,
                'enrolled_students' => 275,
                'completion_rate' => 86,
                'average_rating' => 4.6,
                'total_ratings' => 102,
                'total_reviews' => 77,
                'meta_title' => 'Digital Marketing Strategy & Analytics',
                'meta_title_ar' => 'استراتيجية التسويق الرقمي والتحليلات',
                'meta_description' => 'Design winning digital marketing strategies and measure ROI with analytics.',
                'meta_description_ar' => 'صمم استراتيجيات تسويق رقمي ناجحة وقِس العائد باستخدام التحليلات.',
                'meta_keywords' => 'digital marketing course, marketing analytics, ga4 training',
                'meta_keywords_ar' => 'التسويق الرقمي, تحليلات التسويق, دورة GA4',
                'canonical_url' => 'https://eclass.test/courses/digital-marketing-strategy-analytics',
                'og_title' => 'Design High-Impact Campaigns',
                'og_title_ar' => 'صمم حملات عالية التأثير',
                'og_description' => 'Blueprints for planning, executing, and measuring digital marketing success.',
                'og_description_ar' => 'خطط عملية لتخطيط وتنفيذ وقياس نجاح التسويق الرقمي.',
                'og_image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
                'twitter_title' => 'Digital Marketing Strategy & Analytics',
                'twitter_title_ar' => 'استراتيجية التسويق الرقمي والتحليلات',
                'twitter_description' => 'Master campaign planning, analytics, and reporting with marketing tools.',
                'twitter_description_ar' => 'أتقن تخطيط الحملات والتحليلات والتقارير باستخدام أدوات التسويق.',
                'twitter_image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
                'structured_data' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'Digital Marketing Strategy & Analytics',
                    'description' => 'Plan digital campaigns and measure performance using analytics platforms.',
                    'provider' => $organisation,
                ],
                'structured_data_ar' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'استراتيجية التسويق الرقمي والتحليلات',
                    'description' => 'خطط الحملات الرقمية وقيّم الأداء باستخدام أدوات التحليل.',
                    'provider' => $organisation,
                ],
                'supported_languages' => ['en', 'ar'],
                'default_language' => 'en',
            ],
            [
                'name' => 'Social Media Marketing Mastery',
                'name_ar' => 'إتقان التسويق عبر وسائل التواصل الاجتماعي',
                'description' => 'A fast-paced program to develop channel strategies, automation workflows, and engagement analytics.',
                'description_ar' => 'برنامج سريع لتطوير استراتيجيات المنصات وأتمتة التدفق وتحليلات التفاعل.',
                'category_slug' => 'digital-marketing',
                'duration' => '4 weeks',
                'price' => 349.00,
                'original_price' => 449.00,
                'image' => 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=80',
                'preview_video_url' => 'https://www.youtube.com/watch?v=V8eLsRZL2zk',
                'certificate_template' => null,
                'certificate_text' => null,
                'certificate_text_ar' => null,
                'book' => 'books/social-media-playbook.pdf',
                'what_to_learn' => [
                    'Craft channel-specific content strategies.',
                    'Automate publishing workflows with social suites.',
                    'Measure engagement and community growth.',
                ],
                'what_to_learn_ar' => [
                    'صياغة استراتيجيات محتوى لكل منصة.',
                    'أتمتة عمليات النشر باستخدام أدوات التواصل الاجتماعي.',
                    'قياس التفاعل ونمو المجتمع.',
                ],
                'faq_course' => [
                    [
                        'question' => 'Will we cover influencer collaborations?',
                        'answer' => 'Yes, we include frameworks for identifying and managing influencer partnerships.',
                    ],
                ],
                'faq_course_ar' => [
                    [
                        'question' => 'هل سنغطي التعاون مع المؤثرين؟',
                        'answer' => 'نعم، نعرض أطرًا لتحديد وإدارة شراكات المؤثرين.',
                    ],
                ],
                'requirements' => 'Experience managing at least one social media channel.',
                'requirements_ar' => 'خبرة في إدارة قناة تواصل اجتماعي واحدة على الأقل.',
                'is_featured' => false,
                'show_in_top_discounted' => false,
                'show_in_subscription_bundles' => false,
                'show_in_live_meeting' => false,
                'show_in_recent_courses' => true,
                'is_free' => true,
                'total_lessons' => 20,
                'total_duration_minutes' => 150,
                'enrolled_students' => 610,
                'completion_rate' => 92,
                'average_rating' => 4.2,
                'total_ratings' => 210,
                'total_reviews' => 143,
                'meta_title' => 'Social Media Marketing Mastery',
                'meta_title_ar' => 'إتقان التسويق عبر وسائل التواصل الاجتماعي',
                'meta_description' => 'Grow engaged communities and deliver measurable social media results.',
                'meta_description_ar' => 'نمِ مجتمعات نشطة وحقق نتائج ملموسة في وسائل التواصل.',
                'meta_keywords' => 'social media marketing, influencer strategy, social analytics',
                'meta_keywords_ar' => 'التسويق عبر التواصل الاجتماعي, استراتيجية المؤثرين',
                'canonical_url' => 'https://eclass.test/courses/social-media-marketing-mastery',
                'og_title' => 'Master Social Media Marketing',
                'og_title_ar' => 'أتقن التسويق عبر وسائل التواصل الاجتماعي',
                'og_description' => 'Learn strategies, automation, and analytics for social media success.',
                'og_description_ar' => 'تعلم الاستراتيجيات والأتمتة والتحليلات لنجاح وسائل التواصل الاجتماعي.',
                'og_image' => 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=80',
                'twitter_title' => 'Social Media Marketing Mastery',
                'twitter_title_ar' => 'إتقان التسويق عبر وسائل التواصل الاجتماعي',
                'twitter_description' => 'Content strategy, automation, and analytics for social media managers.',
                'twitter_description_ar' => 'استراتيجيات المحتوى والأتمتة والتحليلات لمديري وسائل التواصل.',
                'twitter_image' => 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=80',
                'structured_data' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'Social Media Marketing Mastery',
                    'description' => 'Develop channel-specific strategies and automation for social media.',
                    'provider' => $organisation,
                ],
                'structured_data_ar' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'إتقان التسويق عبر وسائل التواصل الاجتماعي',
                    'description' => 'طور استراتيجيات خاصة بكل منصة وأتمتة للنشر.',
                    'provider' => $organisation,
                ],
                'supported_languages' => ['en', 'ar'],
                'default_language' => 'en',
            ],
            [
                'name' => 'Product Management Fundamentals',
                'name_ar' => 'أساسيات إدارة المنتجات',
                'description' => 'Frameworks and templates to guide product discovery, prioritization, and go-to-market planning.',
                'description_ar' => 'أطر ونماذج عملية لإرشاد اكتشاف المنتج وتحديد الأولويات وخطط الطرح في السوق.',
                'category_slug' => 'business-management',
                'duration' => '7 weeks',
                'price' => 689.00,
                'original_price' => 829.00,
                'image' => 'https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1200&q=80',
                'preview_video_url' => 'https://www.youtube.com/watch?v=ZKUXc4OfmOY',
                'certificate_template' => 'certificates/product-management.pdf',
                'certificate_text' => 'Certificate of completion for Product Management Fundamentals.',
                'certificate_text_ar' => 'شهادة إكمال في أساسيات إدارة المنتجات.',
                'book' => 'books/product-management-blueprint.pdf',
                'what_to_learn' => [
                    'Define product strategy and vision aligned with company goals.',
                    'Prioritize roadmaps using data-driven frameworks.',
                    'Collaborate with engineering and design through agile rituals.',
                ],
                'what_to_learn_ar' => [
                    'وضع استراتيجية ورؤية المنتج بما يتماشى مع أهداف الشركة.',
                    'تحديد أولويات خارطة الطريق باستخدام أطر قائمة على البيانات.',
                    'التعاون مع الهندسة والتصميم عبر الطقوس الرشيقة.',
                ],
                'faq_course' => [
                    [
                        'question' => 'Is there a capstone product case?',
                        'answer' => 'Yes, you will present a go-to-market plan for a real-world product scenario.',
                    ],
                ],
                'faq_course_ar' => [
                    [
                        'question' => 'هل يوجد مشروع نهائي؟',
                        'answer' => 'نعم، ستقدم خطة طرح سوق لسيناريو منتج واقعي.',
                    ],
                ],
                'requirements' => 'Experience working with product or project teams.',
                'requirements_ar' => 'خبرة في العمل مع فرق المنتج أو المشاريع.',
                'is_featured' => true,
                'show_in_top_discounted' => false,
                'show_in_subscription_bundles' => true,
                'show_in_live_meeting' => false,
                'show_in_recent_courses' => true,
                'is_free' => false,
                'total_lessons' => 42,
                'total_duration_minutes' => 280,
                'enrolled_students' => 230,
                'completion_rate' => 89,
                'average_rating' => 4.7,
                'total_ratings' => 88,
                'total_reviews' => 63,
                'meta_title' => 'Product Management Fundamentals',
                'meta_title_ar' => 'أساسيات إدارة المنتجات',
                'meta_description' => 'Build the skills to lead product discovery, delivery, and go-to-market execution.',
                'meta_description_ar' => 'ابنِ مهارات قيادة اكتشاف المنتج وتقديمه وطريقه إلى السوق.',
                'meta_keywords' => 'product management course, roadmap prioritization, go to market',
                'meta_keywords_ar' => 'إدارة المنتجات, خارطة الطريق, طرح المنتجات',
                'canonical_url' => 'https://eclass.test/courses/product-management-fundamentals',
                'og_title' => 'Lead High-Impact Products',
                'og_title_ar' => 'قد منتجات ذات تأثير كبير',
                'og_description' => 'Frameworks for product strategy, discovery, and stakeholder alignment.',
                'og_description_ar' => 'أطر لإستراتيجية المنتج والاكتشاف ومواءمة أصحاب المصلحة.',
                'og_image' => 'https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1200&q=80',
                'twitter_title' => 'Product Management Fundamentals',
                'twitter_title_ar' => 'أساسيات إدارة المنتجات',
                'twitter_description' => 'Learn strategy, prioritization, and agile collaboration for product teams.',
                'twitter_description_ar' => 'تعلم الاستراتيجية وتحديد الأولويات والتعاون الرشيق لفرق المنتجات.',
                'twitter_image' => 'https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1200&q=80',
                'structured_data' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'Product Management Fundamentals',
                    'description' => 'Develop product strategy skills and collaborate effectively with cross-functional teams.',
                    'provider' => $organisation,
                ],
                'structured_data_ar' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'أساسيات إدارة المنتجات',
                    'description' => 'طوّر مهارات إستراتيجية المنتج وتعاون بكفاءة مع الفرق المتعددة الوظائف.',
                    'provider' => $organisation,
                ],
                'supported_languages' => ['en', 'ar'],
                'default_language' => 'en',
            ],
            [
                'name' => 'Agile Project Management with Scrum',
                'name_ar' => 'إدارة المشاريع الرشيقة باستخدام سكرم',
                'description' => 'Practical guide to leading agile teams with Scrum principles, ceremonies, and metrics.',
                'description_ar' => 'دليل عملي لقيادة الفرق الرشيقة باستخدام مبادئ سكرم وطقوسه ومقاييسه.',
                'category_slug' => 'business-management',
                'duration' => '5 weeks',
                'price' => 459.00,
                'original_price' => 599.00,
                'image' => 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1200&q=80',
                'preview_video_url' => 'https://www.youtube.com/watch?v=9TycLR0TqFA',
                'certificate_template' => null,
                'certificate_text' => null,
                'certificate_text_ar' => null,
                'book' => 'books/agile-project-management-toolkit.pdf',
                'what_to_learn' => [
                    'Facilitate Scrum ceremonies and agile rituals.',
                    'Implement agile metrics like velocity and burn-down.',
                    'Align stakeholders through transparent communication.',
                ],
                'what_to_learn_ar' => [
                    'تيسير اجتماعات سكرم والطقوس الرشيقة.',
                    'تطبيق مقاييس رشيقة مثل السرعة ومخطط الاحتراق.',
                    'مواءمة أصحاب المصلحة من خلال الاتصال الشفاف.',
                ],
                'faq_course' => [
                    [
                        'question' => 'Is there preparation for certification?',
                        'answer' => 'Yes, we include practice assessments aligned with PSM I outcomes.',
                    ],
                ],
                'faq_course_ar' => [
                    [
                        'question' => 'هل توجد تحضيرات للشهادة؟',
                        'answer' => 'نعم، نوفر اختبارات تدريبية متوافقة مع مخرجات PSM I.',
                    ],
                ],
                'requirements' => 'Experience working in project or delivery teams.',
                'requirements_ar' => 'خبرة في العمل ضمن فرق المشاريع أو التسليم.',
                'is_featured' => false,
                'show_in_top_discounted' => true,
                'show_in_subscription_bundles' => false,
                'show_in_live_meeting' => true,
                'show_in_recent_courses' => false,
                'is_free' => false,
                'total_lessons' => 30,
                'total_duration_minutes' => 210,
                'enrolled_students' => 198,
                'completion_rate' => 93,
                'average_rating' => 4.5,
                'total_ratings' => 86,
                'total_reviews' => 54,
                'meta_title' => 'Agile Project Management with Scrum',
                'meta_title_ar' => 'إدارة المشاريع الرشيقة باستخدام سكرم',
                'meta_description' => 'Lead agile delivery teams with Scrum frameworks, metrics, and facilitation skills.',
                'meta_description_ar' => 'قد فرق التسليم الرشيقة باستخدام أطر سكرم والمهارات التيسيرية.',
                'meta_keywords' => 'agile project management, scrum course, psm preparation',
                'meta_keywords_ar' => 'إدارة المشاريع الرشيقة, دورة سكرم',
                'canonical_url' => 'https://eclass.test/courses/agile-project-management-scrum',
                'og_title' => 'Lead High-Performing Agile Teams',
                'og_title_ar' => 'قد فرقًا رشيقة عالية الأداء',
                'og_description' => 'Master Scrum ceremonies, metrics, and stakeholder alignment to deliver value faster.',
                'og_description_ar' => 'أتقن اجتماعات سكرم والمقاييس ومواءمة أصحاب المصلحة لتحقيق قيمة أسرع.',
                'og_image' => 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1200&q=80',
                'twitter_title' => 'Agile Project Management with Scrum',
                'twitter_title_ar' => 'إدارة المشاريع الرشيقة باستخدام سكرم',
                'twitter_description' => 'Gain practical guidance to lead Scrum teams and pass PSM assessments.',
                'twitter_description_ar' => 'احصل على إرشادات عملية لقيادة فرق سكرم واجتياز تقييمات PSM.',
                'twitter_image' => 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1200&q=80',
                'structured_data' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'Agile Project Management with Scrum',
                    'description' => 'Lead agile teams using Scrum practices, metrics, and facilitation techniques.',
                    'provider' => $organisation,
                ],
                'structured_data_ar' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'إدارة المشاريع الرشيقة باستخدام سكرم',
                    'description' => 'قد الفرق الرشيقة باستخدام ممارسات سكرم والمقاييس والتيسير.',
                    'provider' => $organisation,
                ],
                'supported_languages' => ['en', 'ar'],
                'default_language' => 'en',
            ],
            [
                'name' => 'UX/UI Design Essentials',
                'name_ar' => 'أساسيات تصميم تجربة المستخدم والواجهة',
                'description' => 'Master the UX process from research to high-fidelity UI design with collaborative workflows in Figma.',
                'description_ar' => 'أتقن عملية تجربة المستخدم من البحث إلى تصميم الواجهة عالية الجودة مع تدفقات تعاونية في Figma.',
                'category_slug' => 'graphic-design',
                'duration' => '8 weeks',
                'price' => 799.00,
                'original_price' => 949.00,
                'image' => 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
                'preview_video_url' => 'https://www.youtube.com/watch?v=QjaTyC44H7Q',
                'certificate_template' => 'certificates/ux-ui-design.pdf',
                'certificate_text' => 'Certificate of completion for UX/UI Design Essentials.',
                'certificate_text_ar' => 'شهادة إكمال في أساسيات تصميم تجربة المستخدم والواجهة.',
                'book' => 'books/ux-ui-style-guide.pdf',
                'what_to_learn' => [
                    'Conduct user research interviews and usability tests.',
                    'Design high-fidelity interfaces in Figma.',
                    'Collaborate with developers using design systems.',
                ],
                'what_to_learn_ar' => [
                    'إجراء مقابلات المستخدمين واختبارات قابلية الاستخدام.',
                    'تصميم واجهات عالية الجودة في Figma.',
                    'التعاون مع المطورين باستخدام أنظمة التصميم.',
                ],
                'faq_course' => [
                    [
                        'question' => 'Do I need drawing skills?',
                        'answer' => 'No, the focus is on digital design workflows and user research methods.',
                    ],
                ],
                'faq_course_ar' => [
                    [
                        'question' => 'هل أحتاج إلى مهارات في الرسم؟',
                        'answer' => 'لا، التركيز على التدفقات الرقمية وأساليب بحث المستخدم.',
                    ],
                ],
                'requirements' => 'Comfort with design tools and a passion for user-centered design.',
                'requirements_ar' => 'الراحة في استخدام أدوات التصميم والشغف بالتصميم المتمحور حول المستخدم.',
                'is_featured' => true,
                'show_in_top_discounted' => false,
                'show_in_subscription_bundles' => true,
                'show_in_live_meeting' => false,
                'show_in_recent_courses' => true,
                'is_free' => false,
                'total_lessons' => 54,
                'total_duration_minutes' => 360,
                'enrolled_students' => 340,
                'completion_rate' => 76,
                'average_rating' => 4.8,
                'total_ratings' => 152,
                'total_reviews' => 129,
                'meta_title' => 'UX/UI Design Essentials',
                'meta_title_ar' => 'أساسيات تصميم تجربة المستخدم والواجهة',
                'meta_description' => 'Learn UX research, UI design, and prototyping skills with Figma.',
                'meta_description_ar' => 'تعلم أبحاث UX وتصميم UI والنمذجة باستخدام Figma.',
                'meta_keywords' => 'ux design course, ui design, figma training',
                'meta_keywords_ar' => 'تصميم تجربة المستخدم, تصميم الواجهة, دورة Figma',
                'canonical_url' => 'https://eclass.test/courses/ux-ui-design-essentials',
                'og_title' => 'Design Delightful User Experiences',
                'og_title_ar' => 'صمم تجارب مستخدم ممتعة',
                'og_description' => 'Master UX research, UI design, and prototyping workflows.',
                'og_description_ar' => 'أتقن أبحاث UX وتصميم UI وتدفقات النمذجة.',
                'og_image' => 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
                'twitter_title' => 'UX/UI Design Essentials',
                'twitter_title_ar' => 'أساسيات تصميم تجربة المستخدم والواجهة',
                'twitter_description' => 'Hands-on UX research, interface design, and Figma prototyping.',
                'twitter_description_ar' => 'أبحاث UX عملية وتصميم واجهة ونمذجة باستخدام Figma.',
                'twitter_image' => 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
                'structured_data' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'UX/UI Design Essentials',
                    'description' => 'Master UX research and UI design with hands-on Figma projects.',
                    'provider' => $organisation,
                ],
                'structured_data_ar' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'أساسيات تصميم تجربة المستخدم والواجهة',
                    'description' => 'أتقن أبحاث UX وتصميم UI من خلال مشاريع عملية باستخدام Figma.',
                    'provider' => $organisation,
                ],
                'supported_languages' => ['en', 'ar'],
                'default_language' => 'en',
            ],
            [
                'name' => 'Motion Graphics with After Effects',
                'name_ar' => 'الرسوم المتحركة باستخدام After Effects',
                'description' => 'Learn professional motion design techniques to animate typography, logos, and visual effects.',
                'description_ar' => 'تعلم تقنيات التصميم الحركي الاحترافية لتحريك النصوص والشعارات والتأثيرات البصرية.',
                'category_slug' => 'graphic-design',
                'duration' => '6 weeks',
                'price' => 529.00,
                'original_price' => 649.00,
                'image' => 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?auto=format&fit=crop&w=1200&q=80',
                'preview_video_url' => 'https://www.youtube.com/watch?v=j6xD1AonwL8',
                'certificate_template' => null,
                'certificate_text' => null,
                'certificate_text_ar' => null,
                'book' => 'books/motion-graphics-project-files.zip',
                'what_to_learn' => [
                    'Animate typography and logos with dynamic motion.',
                    'Create cinematic transitions and visual effects.',
                    'Export broadcast-ready animations efficiently.',
                ],
                'what_to_learn_ar' => [
                    'تحريك الخطوط والشعارات بحركات ديناميكية.',
                    'إنشاء انتقالات سينمائية وتأثيرات بصرية.',
                    'تصدير الرسوم المتحركة الجاهزة للبث بكفاءة.',
                ],
                'faq_course' => [
                    [
                        'question' => 'Are project files included?',
                        'answer' => 'Yes, you receive layered project files and sound design packs.',
                    ],
                ],
                'faq_course_ar' => [
                    [
                        'question' => 'هل تشمل الدورة ملفات المشاريع؟',
                        'answer' => 'نعم، ستحصل على ملفات مشاريع متعددة الطبقات وحزم تصميم صوتي.',
                    ],
                ],
                'requirements' => 'Adobe Creative Cloud subscription and basic Photoshop skills.',
                'requirements_ar' => 'اشتراك Adobe Creative Cloud ومهارات أساسية في Photoshop.',
                'is_featured' => false,
                'show_in_top_discounted' => false,
                'show_in_subscription_bundles' => false,
                'show_in_live_meeting' => true,
                'show_in_recent_courses' => true,
                'is_free' => false,
                'total_lessons' => 32,
                'total_duration_minutes' => 230,
                'enrolled_students' => 175,
                'completion_rate' => 81,
                'average_rating' => 4.4,
                'total_ratings' => 68,
                'total_reviews' => 49,
                'meta_title' => 'Motion Graphics with After Effects',
                'meta_title_ar' => 'الرسوم المتحركة باستخدام After Effects',
                'meta_description' => 'Create broadcast-ready motion graphics with After Effects and industry workflows.',
                'meta_description_ar' => 'اصنع رسومًا متحركة جاهزة للبث باستخدام After Effects وأدوات الصناعة.',
                'meta_keywords' => 'motion graphics course, after effects training, vfx',
                'meta_keywords_ar' => 'الرسوم المتحركة, After Effects, المؤثرات البصرية',
                'canonical_url' => 'https://eclass.test/courses/motion-graphics-after-effects',
                'og_title' => 'Bring Your Designs to Life',
                'og_title_ar' => 'أضف الحياة لتصاميمك',
                'og_description' => 'Motion design techniques, project files, and workflows for After Effects.',
                'og_description_ar' => 'تقنيات التصميم الحركي وملفات المشاريع وعمليات العمل في After Effects.',
                'og_image' => 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?auto=format&fit=crop&w=1200&q=80',
                'twitter_title' => 'Motion Graphics with After Effects',
                'twitter_title_ar' => 'الرسوم المتحركة باستخدام After Effects',
                'twitter_description' => 'Animate typography, logos, and visual effects with After Effects.',
                'twitter_description_ar' => 'حرك النصوص والشعارات والتأثيرات البصرية باستخدام After Effects.',
                'twitter_image' => 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?auto=format&fit=crop&w=1200&q=80',
                'structured_data' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'Motion Graphics with After Effects',
                    'description' => 'Produce professional motion graphics and visual effects with After Effects.',
                    'provider' => $organisation,
                ],
                'structured_data_ar' => [
                    '@context' => 'https://schema.org',
                    '@type' => 'Course',
                    'name' => 'الرسوم المتحركة باستخدام After Effects',
                    'description' => 'إنتاج رسوم متحركة احترافية وتأثيرات بصرية باستخدام After Effects.',
                    'provider' => $organisation,
                ],
                'supported_languages' => ['en', 'ar'],
                'default_language' => 'en',
            ],
        ];

        $instructorCount = $instructors->count();

        Storage::disk('public')->makeDirectory('courses');
        Storage::disk('public')->makeDirectory('seo');

        foreach ($courses as $index => $courseData) {
            $categoryId = $categoryMap[$courseData['category_slug']] ?? null;

            if (!$categoryId) {
                $this->command?->warn("Category {$courseData['category_slug']} not found. Skipping {$courseData['name']}.");
                continue;
            }

            $slug = Str::slug($courseData['name']);
            $instructor = $instructors[$index % $instructorCount];

            $image = $this->prepareImage($courseData['image'], "courses/{$slug}.jpg");
            $ogImage = $this->prepareImage($courseData['og_image'], "seo/{$slug}-og.jpg");
            $twitterImage = $this->prepareImage($courseData['twitter_image'], "seo/{$slug}-twitter.jpg");

            $payload = array_merge(
                Arr::except($courseData, ['category_slug']),
                [
                    'slug' => $slug,
                    'category_id' => $categoryId,
                    'instructor_id' => $instructor->id,
                    'status' => 'published',
                    'image' => $image ?? $courseData['image'],
                    'og_image' => $ogImage ?? $courseData['og_image'],
                    'twitter_image' => $twitterImage ?? $courseData['twitter_image'],
                ]
            );

            Course::updateOrCreate(
                ['slug' => $slug],
                $payload
            );
        }

        $this->command?->info('Sample courses seeded successfully.');
    }

    protected function prepareImage(?string $value, string $targetPath): ?string
    {
        if (!$value) {
            return null;
        }

        if (!Str::startsWith($value, ['http://', 'https://'])) {
            return $value;
        }

        try {
            $response = Http::timeout(15)->get($value);

            if (!$response->successful()) {
                $this->command?->warn("Failed to fetch image: {$value}");
                return null;
            }

            Storage::disk('public')->put($targetPath, $response->body());
            return $targetPath;
        } catch (\Throwable $exception) {
            $this->command?->warn("Error downloading image {$value}: {$exception->getMessage()}");
            return null;
        }
    }
}
